# Generated by Django 2.1.5 on 2019-03-08 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190308_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='last_modified',
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.TextField(choices=[('A', 'A'), ('I', 'I')], db_index=True, default='A', max_length=2),
        ),
        migrations.AlterField(
            model_name='category',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='reorder_quantity',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='reorder_trigger',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product'),
        ),
    ]
